name: Changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  check:
    if: |
      !contains(github.event.pull_request.head.ref, 'changeset-release') &&
      !contains(github.event.pull_request.labels.*.name, 'skip changelog')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node with v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Check for Changeset
        id: check-for-changeset
        continue-on-error: true
        run: npx @changesets/cli status --since="origin/main"

      # - name: Post PR comment
      #   if: steps.check-for-changeset.outcome == 'failure'
      #   uses: Shopify/github-actions/comment-on-pr-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     msg: "###  ⚠️  No Changeset found ⚠️ \n\n Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, please add a `skip changelog` label. \n\n **If these changes should result in a version bump, please run `yarn changeset` to add a changeset.** \n\n Take a look at our [documentation](https://github.com/Shopify/online-store-ui/tree/main/.changeset) to understand how we use changesets in online-store-ui"
      #     check_for_duplicate_msg: true
      #     duplicate_msg_pattern: Merging this PR will not cause a version bump for any packages

      - name: Set PR check output to failure
        if: steps.check-for-changeset.outcome == 'failure'
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            core.setFailed('No changeset found. If these changes should result in a version bump, please run yarn changeset to add a changeset. If these changes should not result in a new version, please add a skip changelog label.');